// <auto-generated />
namespace SaleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Ayxan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ayxan));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161238490_Ayxan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
